CREATE TABLE Subjects
(
	SubjectID INT PRIMARY KEY IDENTITY NOT NULL,
	SubjectName VARCHAR(50) NOT NULL
)

CREATE TABLE Majors
(
	MajorID INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Students
(
	StudentID INT PRIMARY KEY IDENTITY NOT NULL,
	StudentNumber CHAR(10) NOT NULL,
	StudentName NVARCHAR(30) NOT NULL,
	MajorID INT NOT NULL,
	CONSTRAINT FK_Student_MajorID_MajorsID FOREIGN KEY (MajorID)
	REFERENCES Majors(MajorID)
)

CREATE TABLE Agenda
(
	StudentID INT NOT NULL,
	SubjectID INT NOT NULL,
	CONSTRAINT PK_StudentID_SubjectID PRIMARY KEY (StudentID,SubjectID),
	CONSTRAINT FK_Agenda_StudentID_Students FOREIGN KEY (StudentID)
	REFERENCES Students(StudentID),
	CONSTRAINT FK_Agenda_SubjectID_Subjects FOREIGN KEY (SubjectID)
	REFERENCES Subjects(SubjectID)
)

CREATE TABLE Payments
(
	PaymentID INT PRIMARY KEY IDENTITY NOT NULL,
	PaymentDate DATETIME NOT NULL,
	PaymentAmount DECIMAL(15,2) NOT NULL,
	StudentID INT NOT NULL,
	CONSTRAINT FK_Payments_StudentsID FOREIGN KEY (StudentID)
	REFERENCES Students(StudentID)
)